name: Fetch CPU Library
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  libfetch:
    name: Fetch Library
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Fetch CPU Library
      run: |
        python ./main.py
    - name: Upload Rule File
      uses: actions/upload-artifact@v3
      with:
        name: cpu_lib
        path: ./cpu_lib.yaml
    - name: Upload to server
      env:
        PRIVATE_KEY: ${{ secrets.ID_RSA_LS }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.USER }}
        HOST: ${{ secrets.HOST }}
        DESTINATION: ${{ secrets.DESTINATION }}
      run: |
        echo "$PRIVATE_KEY" >> ./id_rsa_ls
        chmod 600 ./id_rsa_ls
        scp -P $SSH_PORT -i ./id_rsa_ls -o StrictHostKeyChecking=no ./cpu_lib.yaml $USER@$HOST:$DESTINATION/
